esphome:
  name: ${name}
  friendly_name: ${area} ${friendly_name}
  name_add_mac_suffix: False
  area: ${area}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} Fallback Hotspot"
    password: !secret fallback_hotspot_password

captive_portal:

# Disable web server if the device is underpowered or lacks resources
web_server:
  port: 80
  auth: 
    username: !secret web_server_username
    password: !secret web_server_password

sensor:
  - platform: uptime
    name: Uptime Sensor
    id: uptime_sensor
    entity_category: diagnostic
    # internal: true
    disabled_by_default: false
    unit_of_measurement: s
    update_interval: 60s
